/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Projectdraft;

import com.sacco.classes.Admin;
import com.sacco.classes.Application;
import com.sacco.classes.Member;
import java.sql.Date;
import java.sql.SQLException;
import javax.security.auth.login.AccountException;
import javax.swing.JOptionPane;

/**
 *
 * @author Antony
 */
public class AdminEditMember extends javax.swing.JInternalFrame {

    Admin _admin;
    Member _member;
    long selectedMemberID;

    /**
     * Creates new form NewJInternalFrame
     */
    public AdminEditMember() {
        initComponents();

        try {
            this._admin = new Admin();
            this._member = new Member();
            // TODO add your handling code here:
            _admin.DisplayAllMembers(jComboBoxMembers);
            EditMode(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL error", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (AccountException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Access denied", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    private void EditMode(boolean edit) {
        jTextFieldAddress.setEditable(edit);
        jTextFieldDob.setEditable(edit);
        jTextFieldFname.setEditable(edit);
        jTextFieldMobileNo.setEditable(edit);
        jTextFieldEmail.setEditable(edit);
        jPasswordNewPassword.setEditable(edit);
        jPasswordNewRptPass.setEditable(edit);
        jTextId.setEditable(edit);
        jTextFieldLname.setEditable(edit);
        jButtonSavePassword.setEnabled(edit);
        jButtonSaveDetails.setEnabled(edit);
        // not required
        jTextFieldDateChanged.setEditable(false);
        jTextFieldDateRegistered.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBoxMembers = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jButtonSavePassword = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordNewPassword = new javax.swing.JPasswordField();
        jPasswordNewRptPass = new javax.swing.JPasswordField();
        jToggleButtonEdit = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDateChanged = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDateRegistered = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jTextFieldMobileNo = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldDob = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonSaveDetails = new javax.swing.JButton();
        jButtonDeactivate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonActivate = new javax.swing.JButton();
        jButtonViewMemberPayments = new javax.swing.JButton();
        jButtonViewMemberLoans = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("(Administrator) Edit Member");
        setDoubleBuffered(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "lookup Available members by their ID's", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jComboBoxMembers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxMembers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMembersItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBoxMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBoxMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit User password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jButtonSavePassword.setText("Save");
        jButtonSavePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePasswordActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("password");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Repeat password");

        jPasswordNewPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPasswordNewRptPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSavePassword))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordNewRptPass, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jPasswordNewRptPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSavePassword))
        );

        jToggleButtonEdit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButtonEdit.setText("Toggle Edit Mode");
        jToggleButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEditActionPerformed(evt);
            }
        });

        jPanel1.setToolTipText("");

        jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonMale.setText("Male");

        jRadioButtonFemale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonFemale.setText("Female");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Date Last Edited");

        jTextFieldDateChanged.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Date Registred");

        jTextFieldDateRegistered.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(43, 43, 43)
                        .addComponent(jTextFieldDateRegistered))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(81, 81, 81)
                        .addComponent(jRadioButtonMale)
                        .addGap(70, 70, 70)
                        .addComponent(jRadioButtonFemale)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33)
                        .addComponent(jTextFieldDateChanged)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMale)
                    .addComponent(jRadioButtonFemale)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDateChanged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Member Info"));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        jTextFieldFname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Date of birth");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Mobile no");

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Email");

        jTextFieldLname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldMobileNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 15, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(97, 97, 97))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextId, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(jTextFieldFname)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMobileNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jTextFieldAddress)
                            .addComponent(jTextFieldEmail)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldDob)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(69, 69, 69))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jButtonSaveDetails.setText("Save new Details");
        jButtonSaveDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDetailsActionPerformed(evt);
            }
        });

        jButtonDeactivate.setText("Deactivate Account");
        jButtonDeactivate.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonDeactivate.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButtonDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeactivateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete Member");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonActivate.setText("Activate Account");
        jButtonActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonActivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jButtonSaveDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDeactivate)
                    .addComponent(jButtonSaveDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jButtonActivate)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonDelete)
                .addContainerGap())
        );

        jButtonViewMemberPayments.setText("View Payments");

        jButtonViewMemberLoans.setText("View loans");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonViewMemberLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButtonViewMemberPayments))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtonEdit)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jToggleButtonEdit)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonViewMemberPayments)
                            .addComponent(jButtonViewMemberLoans))))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMembersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMembersItemStateChanged
        try {
            // TODO add your handling code here:
            // fill in the textfields
            _member.getMemberInfo(_member, Long.parseLong(jComboBoxMembers.getSelectedItem().toString()));
            jTextId.setText(jComboBoxMembers.getSelectedItem().toString());
            jTextFieldFname.setText(_member.getFirstname());
            jTextFieldLname.setText(_member.getLastname());
            jTextFieldDob.setText(_member.getDob().toString());
            jTextFieldAddress.setText(_member.getAddress());
            jTextFieldDateRegistered.setText(_member.getRegisteredDate().toString());
            jTextFieldDateChanged.setText(_member.getLastModifiedDate().toString());
            jTextFieldMobileNo.setText(Integer.toString(_member.getMobileno()));
            jTextFieldEmail.setText(_member.getEmail());
            // block or unblock the activate/deactivate account button
            if (_member.getAccountStatus()) {
                jButtonActivate.setEnabled(false);
                jButtonActivate.setToolTipText("The account is already activated");
                jButtonDeactivate.setEnabled(true);
            } else {
                jButtonActivate.setEnabled(true);
                jButtonDeactivate.setToolTipText("Account has not been deactivated");
                jButtonDeactivate.setEnabled(false);
            }
            selectedMemberID = Long.parseLong(jComboBoxMembers.getSelectedItem().toString());
            if (selectedMemberID == Member.getId()) {
                jButtonDeactivate.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonDelete.setToolTipText("You can delete any other account but not your own");
                jButtonDeactivate.setToolTipText("You can deactivate any other account but not your own");
            }
            // auto mark the gender
            if (_member.getGender().equals("Male")) {
                jRadioButtonMale.setSelected(true);
                jRadioButtonFemale.setSelected(false);
            } else {
                jRadioButtonMale.setSelected(false);
                jRadioButtonFemale.setSelected(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL Error", "Error", JOptionPane.ERROR_MESSAGE);
            //this.dispose();
        }
    }//GEN-LAST:event_jComboBoxMembersItemStateChanged

    private void jButtonSavePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePasswordActionPerformed
        // TODO add your handling code here:
        //check if password strings are the same. common logic
        String passString;
        if (!Application.CheckPasswordEquality(jPasswordNewPassword, jPasswordNewRptPass)) {
            JOptionPane.showMessageDialog(rootPane, "The passwords don't match", "Misimatching passwords", JOptionPane.ERROR_MESSAGE);
            jPasswordNewPassword.requestFocus();
            return;
        } else {
            passString = new String(jPasswordNewPassword.getPassword());
            // check the password length
            if (passString.length() <= 5 || passString.length() > 30) {
                JOptionPane.showMessageDialog(rootPane, "length should be between 6 and 30 characters", "Wrong password length", JOptionPane.ERROR_MESSAGE);
                jPasswordNewPassword.requestFocus();
                return;
            }

        }

        try {
            // save the edited password
            if (_member.EditPassword(passString, Long.parseLong(jComboBoxMembers.getSelectedItem().toString()))) {
                JOptionPane.showMessageDialog(rootPane, "Done!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Could not save the password. Please try again", "Action failed", JOptionPane.ERROR_MESSAGE);
            }
        } catch (AccountException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Not allowed", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSavePasswordActionPerformed

    private void jToggleButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEditActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonEdit.isSelected()) {
            EditMode(true);
        } else {
            EditMode(false);
        }
    }//GEN-LAST:event_jToggleButtonEditActionPerformed

    private void jButtonSaveDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDetailsActionPerformed
        // TODO add your handling code here:

        // the member names. we check if user input is ok
        if (Application.ValidateEmptyValue(jTextFieldFname, "please enter a value for firstname")) {
            _member.setFirstname(jTextFieldFname.getText());
        } else {
            // we halt execution of the function
            return;
        }
        if (Application.ValidateEmptyValue(jTextFieldLname, "please enter a value for lastname")) {
            _member.setLastname(jTextFieldLname.getText());
        } else {
            return;
        }

        // set the gender
        if (jRadioButtonFemale.isSelected()) {
            _member.setGender(jRadioButtonFemale.getText());
        } else {
            _member.setGender(jRadioButtonMale.getText());
        }

        // the date of birth. please bear with this one. I couldn't find _admin better way that worked
        Date d = Application.CheckDateInput(jTextFieldDob.getText());
        if (d == null) {
            JOptionPane.showMessageDialog(rootPane, "please enter a date in the format of yyyy-mm-dd", "Invalid date", JOptionPane.ERROR_MESSAGE);
            jTextFieldDob.requestFocus();
            return;
        } else {
            _member.setDob(d);
        }

        // validate for didgits
        int mobileno = Application.CheckIfNumber(jTextFieldMobileNo.getText());
        if (mobileno == -1) {
            JOptionPane.showMessageDialog(rootPane, "please enter valid value for phone number", "Invalid phone number", JOptionPane.ERROR_MESSAGE);
            jTextFieldMobileNo.requestFocus();
            return;
        } else {
            _member.setMobileno(mobileno);
        }

        // the address
        if (Application.ValidateEmptyValue(jTextFieldAddress, "please enter a value for Address")) {
            _member.setAddress(jTextFieldAddress.getText());
        } else {
            return;
        }

        // the email
        if (Application.ValidateEmptyValue(jTextFieldEmail, "please enter an email address")) {
            _member.setEmail(jTextFieldEmail.getText().trim());
        } else {
            return;
        }

        try {
            // edit the info
            if (_member.EditMemberInfo(_member)) {
                JOptionPane.showMessageDialog(rootPane, "Success ", "Error", JOptionPane.INFORMATION_MESSAGE);
                _admin.DisplayAllMembers(jComboBoxMembers);
            } else {
                JOptionPane.showMessageDialog(rootPane, "No update was made", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (AccountException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Access denied", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Operation failed " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveDetailsActionPerformed

    private void jButtonDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeactivateActionPerformed
        selectedMemberID = Long.parseLong(jComboBoxMembers.getSelectedItem().toString());
        if (selectedMemberID == Member.getId()) {
            jButtonDeactivate.setEnabled(false);
            jButtonDeactivate.setToolTipText("You can deactivate any account but not your own");
        }
        try {
            int reply = JOptionPane.showConfirmDialog(rootPane, "When the account is deactivated, the user wouldn't be able to login. Continue?", "prompt", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                if (_admin.AlterMemberAccount(selectedMemberID, 0)) {
                    JOptionPane.showMessageDialog(rootPane, "Action was a success", "Account Deactivation", JOptionPane.INFORMATION_MESSAGE);
                    // log them out
                    // Admin.Logout(selectedMemberID);
                    // refresh combo box
                    _admin.DisplayAllMembers(jComboBoxMembers);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Operation failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL error", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (AccountException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Access denied", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeactivateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed

        selectedMemberID = Long.parseLong(jComboBoxMembers.getSelectedItem().toString());
        // stop an obviously destructive action
        if (selectedMemberID == Member.getId()) {
            JOptionPane.showMessageDialog(rootPane, "Surely, don't do this. It's your own account", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        try {
            int reply = JOptionPane.showConfirmDialog(rootPane,
                    "<html>"
                    + "<b>This will completely erase a member's existence in the sacco.</b>"
                    + "<br><p><b>All loans, contributions, etc will be erased.</b>"
                    + "<br><i>You can try deactivating their account instead.</i></p>"
                    + "<br><p><b>Are you sure you want to do this?</b></p>"
                    + "</html>", "Delete member prompt", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                if (_admin.AlterMemberAccount(selectedMemberID, 4)) {
                    JOptionPane.showMessageDialog(rootPane, "Action was a success", "Account deletion", JOptionPane.INFORMATION_MESSAGE);
                    // refresh combo box
                    _admin.DisplayAllMembers(jComboBoxMembers);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Operation failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL error", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (AccountException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Access denied", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateActionPerformed
        // TODO add your handling code here:
        selectedMemberID = Long.parseLong(jComboBoxMembers.getSelectedItem().toString());
        try {
            int reply = JOptionPane.showConfirmDialog(rootPane, "When the account is activated, the user would now be able to login. Continue?", "prompt", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                if (_admin.AlterMemberAccount(selectedMemberID, 2)) {
                    JOptionPane.showMessageDialog(rootPane, "Action was a success", "Account Activation", JOptionPane.INFORMATION_MESSAGE);
                    // refresh combo box
                    _admin.DisplayAllMembers(jComboBoxMembers);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Operation failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQl error occured", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (AccountException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Access denied", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonActivateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActivate;
    private javax.swing.JButton jButtonDeactivate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSaveDetails;
    private javax.swing.JButton jButtonSavePassword;
    private javax.swing.JButton jButtonViewMemberLoans;
    private javax.swing.JButton jButtonViewMemberPayments;
    private javax.swing.JComboBox jComboBoxMembers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordNewPassword;
    private javax.swing.JPasswordField jPasswordNewRptPass;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldDateChanged;
    private javax.swing.JTextField jTextFieldDateRegistered;
    private javax.swing.JTextField jTextFieldDob;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldMobileNo;
    private javax.swing.JTextField jTextId;
    private javax.swing.JToggleButton jToggleButtonEdit;
    // End of variables declaration//GEN-END:variables
}
