/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Projectdraft;

import com.sacco.classes.Application;
import com.sacco.classes.Database;
import com.sacco.classes.Member;
import java.sql.SQLException;
import javax.security.auth.login.AccountException;
import javax.swing.JOptionPane;

/**
 *
 * @author CJ
 */
public class MembersIndex extends javax.swing.JFrame {

    Member _member = new Member();

    /**
     * Creates new form MembersHomePage
     */
    public MembersIndex() {
        initComponents();

        // disable administrative controls
        jMenuAdministrator.setVisible(false);
        jMenuSec.setVisible(false);
        jMenuTreasuere.setVisible(false);
        try {
            //jLabel1.setText("Welcome. You are logged in as "+_member.getFirstname()+" .The time now is "+Helper.dateFromLong(Long.MIN_VALUE));
            // check if a user is an admin
            if (_member.checkUserPosition() == 1) {
                // am an admin, so enable my menu
                //JOptionPane.showMessageDialog(rootPane, _member.checkIfUserIsAdmin());
                jMenuAdministrator.setVisible(true);
            }
            if (_member.checkUserPosition() == 2) {
                jMenuSec.setVisible(true);
            } else {
                jMenuSec.setVisible(false);
            }
            if (_member.checkUserPosition() == 3) {
                jMenuTreasuere.setVisible(true);
            } else {
                jMenuTreasuere.setVisible(false);
            }
        } catch (SQLException ex) {
            // we just disable all 'important' menus
            jMenuAdministrator.setVisible(false);
            jMenuSec.setVisible(false);
            jMenuTreasuere.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuMembers = new javax.swing.JMenu();
        jMenuMember = new javax.swing.JMenu();
        jMenuItemMemberInfo = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMyPassword = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuLoans = new javax.swing.JMenu();
        jMenuItemApplyLoan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRepayLoan = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCheckLoanStatus = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLoanPayment = new javax.swing.JMenuItem();
        jMenuContrib = new javax.swing.JMenu();
        jMenuItemMakeContrib = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemViewMyContributions = new javax.swing.JMenuItem();
        jMenuAdministrator = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItemAllMembersMenu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemNewMember = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMembersList = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemViewLoans = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenu12 = new javax.swing.JMenu();
        jMenuItemViewContrib = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemApproveDenyContrib = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenu13 = new javax.swing.JMenu();
        jMenuItemEditInterest = new javax.swing.JMenuItem();
        jMenuSec = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuTreasuere = new javax.swing.JMenu();
        jMenuItemViewTotalLoans = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenu7.setText("jMenu7");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sacco Application");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setForeground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setText("Open");
        jMenuFile.add(jMenuItem15);
        jMenuFile.add(jSeparator10);

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLogout.setText("Log Out");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogout);

        jMenuBar2.add(jMenuFile);

        jMenuMembers.setText("Members");

        jMenuMember.setText("My Profile");

        jMenuItemMemberInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemMemberInfo.setText("Edit My Info");
        jMenuItemMemberInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMemberInfoActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemMemberInfo);
        jMenuMember.add(jSeparator17);

        jMenuItemMyPassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemMyPassword.setText("Edit My Password");
        jMenuItemMyPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMyPasswordActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemMyPassword);
        jMenuMember.add(jSeparator18);

        jMenuMembers.add(jMenuMember);
        jMenuMembers.add(jSeparator3);

        jMenuItem9.setText("Login Info");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuMembers.add(jMenuItem9);

        jMenuBar2.add(jMenuMembers);

        jMenuLoans.setText("Loans");

        jMenuItemApplyLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemApplyLoan.setText("Apply for Loan");
        jMenuItemApplyLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApplyLoanActionPerformed(evt);
            }
        });
        jMenuLoans.add(jMenuItemApplyLoan);
        jMenuLoans.add(jSeparator7);

        jMenuItemRepayLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRepayLoan.setText("Repay Loan");
        jMenuItemRepayLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepayLoanActionPerformed(evt);
            }
        });
        jMenuLoans.add(jMenuItemRepayLoan);
        jMenuLoans.add(jSeparator8);

        jMenuItemCheckLoanStatus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCheckLoanStatus.setText("View My loan information");
        jMenuItemCheckLoanStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheckLoanStatusActionPerformed(evt);
            }
        });
        jMenuLoans.add(jMenuItemCheckLoanStatus);
        jMenuLoans.add(jSeparator12);

        jMenuItemLoanPayment.setText("View Loan Payments");
        jMenuItemLoanPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoanPaymentActionPerformed(evt);
            }
        });
        jMenuLoans.add(jMenuItemLoanPayment);

        jMenuBar2.add(jMenuLoans);

        jMenuContrib.setText("Contributions");

        jMenuItemMakeContrib.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemMakeContrib.setText("Make Contribution");
        jMenuItemMakeContrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMakeContribActionPerformed(evt);
            }
        });
        jMenuContrib.add(jMenuItemMakeContrib);
        jMenuContrib.add(jSeparator2);

        jMenuItemViewMyContributions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemViewMyContributions.setText("View my contributions");
        jMenuItemViewMyContributions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewMyContributionsActionPerformed(evt);
            }
        });
        jMenuContrib.add(jMenuItemViewMyContributions);

        jMenuBar2.add(jMenuContrib);

        jMenuAdministrator.setText("Administrator");

        jMenu11.setText("Manage Members");

        jMenuItemAllMembersMenu.setText("All Members");
        jMenuItemAllMembersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAllMembersMenuActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItemAllMembersMenu);
        jMenu11.add(jSeparator4);

        jMenuItemNewMember.setText("New Member");
        jMenuItemNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewMemberActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItemNewMember);
        jMenu11.add(jSeparator14);

        jMenuItemMembersList.setText("Members List");
        jMenuItemMembersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMembersListActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItemMembersList);

        jMenuAdministrator.add(jMenu11);
        jMenuAdministrator.add(jSeparator13);

        jMenu5.setText("Manage Loans");

        jMenuItemViewLoans.setText("View Member Loans");
        jMenu5.add(jMenuItemViewLoans);

        jMenuAdministrator.add(jMenu5);
        jMenuAdministrator.add(jSeparator19);

        jMenu12.setText("Manage Contributions");

        jMenuItemViewContrib.setText("View Member Contributions");
        jMenu12.add(jMenuItemViewContrib);
        jMenu12.add(jSeparator6);

        jMenuItemApproveDenyContrib.setText("Approve/Revoke Contribitions");
        jMenuItemApproveDenyContrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApproveDenyContribActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItemApproveDenyContrib);

        jMenuAdministrator.add(jMenu12);
        jMenuAdministrator.add(jSeparator20);

        jMenu13.setText("App Settings");

        jMenuItemEditInterest.setText("Edit Interest");
        jMenuItemEditInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditInterestActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItemEditInterest);

        jMenuAdministrator.add(jMenu13);

        jMenuBar2.add(jMenuAdministrator);

        jMenuSec.setText("Secretary");

        jMenuItem4.setText("Upload Minutes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuSec.add(jMenuItem4);

        jMenuBar2.add(jMenuSec);

        jMenuTreasuere.setText("Treasurer");

        jMenuItemViewTotalLoans.setText("View Loan & contribution reports");
        jMenuItemViewTotalLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewTotalLoansActionPerformed(evt);
            }
        });
        jMenuTreasuere.add(jMenuItemViewTotalLoans);

        jMenuBar2.add(jMenuTreasuere);

        jMenu9.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Report Issue");
        jMenuItem2.setRolloverEnabled(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem2);
        jMenu9.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("About");
        jMenu9.add(jMenuItem1);
        jMenu9.add(jSeparator5);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("User Manual");
        jMenu9.add(jMenuItem14);

        jMenuBar2.add(jMenu9);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMembersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMembersListActionPerformed
        AllMembers app = new AllMembers();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemMembersListActionPerformed

    private void jMenuItemApplyLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApplyLoanActionPerformed
        ApplyForLoan app = new ApplyForLoan();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemApplyLoanActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        if (Member.Logout()) {
            JOptionPane.showMessageDialog(rootPane, "Youve logged out", "Bye", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new LoginScreen().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "System is experiencing problems. please try again");
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewMemberActionPerformed
        // TODO add your handling code here:
        new AddMember().setVisible(true);
    }//GEN-LAST:event_jMenuItemNewMemberActionPerformed

    private void jMenuItemCheckLoanStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheckLoanStatusActionPerformed
        // TODO add your handling code here:
        DisplayLoanInformation app = new DisplayLoanInformation();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemCheckLoanStatusActionPerformed

    private void jMenuItemMakeContribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMakeContribActionPerformed
        // TODO add your handling code here:
        MakeContribution app = new MakeContribution();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemMakeContribActionPerformed

    private void jMenuItemRepayLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepayLoanActionPerformed
        // TODO add your handling code here:
        RepayLoan adm = new RepayLoan();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemRepayLoanActionPerformed

    private void jMenuItemMemberInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMemberInfoActionPerformed
        // TODO add your handling code here:
        EditMember adm = new EditMember();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemMemberInfoActionPerformed

    private void jMenuItemMyPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMyPasswordActionPerformed
        // TODO add your handling code here:
        EditPassword adm = new EditPassword();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemMyPasswordActionPerformed

    private void jMenuItemEditInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditInterestActionPerformed
        // TODO add your handling code here:
        EditLoanInterest app = new EditLoanInterest();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditInterestActionPerformed

    private void jMenuItemAllMembersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAllMembersMenuActionPerformed
        AdminEditMember adm = new AdminEditMember();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemAllMembersMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        SubmittQuery adm = new SubmittQuery();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(this.getContentPane(), "Are you sure you want to exit?", "prompt", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (reply != JOptionPane.NO_OPTION) {
            dispose();
            Application.Exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "<html> <p>Your User Id is </p>" + Member.getId() + "<br><p> You are logged in as </p>" + _member.getFirstname() + "</html>");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItemViewMyContributionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewMyContributionsActionPerformed
        // TODO add your handling code here:
        ViewMyTotalContributions adm = new ViewMyTotalContributions();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewMyContributionsActionPerformed

    private void jMenuItemApproveDenyContribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApproveDenyContribActionPerformed
        // TODO add your handling code here:
        ApproveContribution adm = new ApproveContribution();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemApproveDenyContribActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CreateMinutes adm = new CreateMinutes();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemViewTotalLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewTotalLoansActionPerformed
        // TODO add your handling code here:
        ViewLoanAndContributionReport adm = new ViewLoanAndContributionReport();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewTotalLoansActionPerformed

    private void jMenuItemLoanPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoanPaymentActionPerformed
        // TODO add your handling code here:
        ViewLoanPayments adm = new ViewLoanPayments();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoanPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MembersIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            if (!Member.CheckLoggedIn()) {
                JOptionPane.showMessageDialog(null, "Please login first", "Access denied", JOptionPane.ERROR_MESSAGE);
                new LoginScreen().setVisible(true);
            } else {
                new MembersIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAdministrator;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuContrib;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAllMembersMenu;
    private javax.swing.JMenuItem jMenuItemApplyLoan;
    private javax.swing.JMenuItem jMenuItemApproveDenyContrib;
    private javax.swing.JMenuItem jMenuItemCheckLoanStatus;
    private javax.swing.JMenuItem jMenuItemEditInterest;
    private javax.swing.JMenuItem jMenuItemLoanPayment;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemMakeContrib;
    private javax.swing.JMenuItem jMenuItemMemberInfo;
    private javax.swing.JMenuItem jMenuItemMembersList;
    private javax.swing.JMenuItem jMenuItemMyPassword;
    private javax.swing.JMenuItem jMenuItemNewMember;
    private javax.swing.JMenuItem jMenuItemRepayLoan;
    private javax.swing.JMenuItem jMenuItemViewContrib;
    private javax.swing.JMenuItem jMenuItemViewLoans;
    private javax.swing.JMenuItem jMenuItemViewMyContributions;
    private javax.swing.JMenuItem jMenuItemViewTotalLoans;
    private javax.swing.JMenu jMenuLoans;
    private javax.swing.JMenu jMenuMember;
    private javax.swing.JMenu jMenuMembers;
    private javax.swing.JMenu jMenuSec;
    private javax.swing.JMenu jMenuTreasuere;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
