/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Projectdraft;

import com.sacco.classes.Application;
import com.sacco.classes.Member;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author CJ
 */
public class MembersIndex extends javax.swing.JFrame {

    Member m = new Member();

    /**
     * Creates new form MembersHomePage
     */
    public MembersIndex() {
        initComponents();

        // disable administrative controls
        jMenuAdministrator.setVisible(false);

        try {
            //jLabel1.setText("Welcome. You are logged in as "+m.getFirstname()+" .The time now is "+Helper.dateFromLong(Long.MIN_VALUE));
            // check if a user is an admin
            if (m.checkIfUserIsAdmin()) {
                // am an admin, so enable my menu
                //JOptionPane.showMessageDialog(rootPane, m.checkIfUserIsAdmin());
                jMenuAdministrator.setVisible(true);
            }
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Application error");
            jMenuAdministrator.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuMember = new javax.swing.JMenu();
        jMenuItemMemberInfo = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMyPassword = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemApplyLoan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRepayLoan = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCheckLoanStatus = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItemMakeContrib = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemViewMyContributions = new javax.swing.JMenuItem();
        jMenuAdministrator = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItemAllMembersMenu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemNewMember = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMembersList = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemViewLoans = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenu12 = new javax.swing.JMenu();
        jMenuItemViewContrib = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemApproveDenyContrib = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        jMenu13 = new javax.swing.JMenu();
        jMenuItemEditInterest = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuReports = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenu7.setText("jMenu7");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sacco Application");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setForeground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );

        jMenu4.setText("File");

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setText("Open");
        jMenu4.add(jMenuItem15);
        jMenu4.add(jSeparator10);

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLogout.setText("Log Out");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemLogout);

        jMenuBar2.add(jMenu4);

        jMenu8.setText("Members");

        jMenuMember.setText("My Profile");

        jMenuItemMemberInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemMemberInfo.setText("Edit My Info");
        jMenuItemMemberInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMemberInfoActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemMemberInfo);
        jMenuMember.add(jSeparator17);

        jMenuItemMyPassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemMyPassword.setText("Edit My Password");
        jMenuItemMyPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMyPasswordActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemMyPassword);
        jMenuMember.add(jSeparator18);

        jMenu8.add(jMenuMember);
        jMenu8.add(jSeparator3);

        jMenuItem9.setText("Login Info");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuBar2.add(jMenu8);

        jMenu2.setText("Member Loans");

        jMenuItemApplyLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemApplyLoan.setText("Apply for Loan");
        jMenuItemApplyLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApplyLoanActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemApplyLoan);
        jMenu2.add(jSeparator7);

        jMenuItemRepayLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRepayLoan.setText("Repay Loan");
        jMenuItemRepayLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepayLoanActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRepayLoan);
        jMenu2.add(jSeparator8);

        jMenuItemCheckLoanStatus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCheckLoanStatus.setText("Loan Status");
        jMenuItemCheckLoanStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheckLoanStatusActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCheckLoanStatus);

        jMenuBar2.add(jMenu2);

        jMenu10.setText("Member Contributions");

        jMenuItemMakeContrib.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemMakeContrib.setText("Make Contribution");
        jMenuItemMakeContrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMakeContribActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItemMakeContrib);
        jMenu10.add(jSeparator2);

        jMenuItemViewMyContributions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemViewMyContributions.setText("View my contributions");
        jMenu10.add(jMenuItemViewMyContributions);

        jMenuBar2.add(jMenu10);

        jMenuAdministrator.setText("Administrator");

        jMenu11.setText("Manage Members");

        jMenuItemAllMembersMenu.setText("All Members");
        jMenuItemAllMembersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAllMembersMenuActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItemAllMembersMenu);
        jMenu11.add(jSeparator4);

        jMenuItemNewMember.setText("New Member");
        jMenuItemNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewMemberActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItemNewMember);
        jMenu11.add(jSeparator14);

        jMenuItemMembersList.setText("Members List");
        jMenuItemMembersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMembersListActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItemMembersList);

        jMenuAdministrator.add(jMenu11);
        jMenuAdministrator.add(jSeparator13);

        jMenu5.setText("Manage Loans");

        jMenuItemViewLoans.setText("View Member Loans");
        jMenu5.add(jMenuItemViewLoans);

        jMenuAdministrator.add(jMenu5);
        jMenuAdministrator.add(jSeparator19);

        jMenu12.setText("Manage Contributions");

        jMenuItemViewContrib.setText("View Member Contributions");
        jMenu12.add(jMenuItemViewContrib);
        jMenu12.add(jSeparator6);

        jMenuItemApproveDenyContrib.setText("Approve/Revoke Contribitions");
        jMenu12.add(jMenuItemApproveDenyContrib);

        jMenuAdministrator.add(jMenu12);
        jMenuAdministrator.add(jSeparator20);

        jMenu13.setText("App Settings");

        jMenuItemEditInterest.setText("Edit Interest");
        jMenuItemEditInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditInterestActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItemEditInterest);

        jMenuAdministrator.add(jMenu13);
        jMenuAdministrator.add(jSeparator9);

        jMenuReports.setText("Reports");

        jMenuItem8.setText("Trial Balance");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuReports.add(jMenuItem8);
        jMenuReports.add(jSeparator15);

        jMenuItem6.setText("Income Statement");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuReports.add(jMenuItem6);
        jMenuReports.add(jSeparator16);

        jMenuItem7.setText("Balance Sheet");
        jMenuReports.add(jMenuItem7);

        jMenuAdministrator.add(jMenuReports);

        jMenuBar2.add(jMenuAdministrator);

        jMenu9.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Report Issue");
        jMenuItem2.setRolloverEnabled(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem2);
        jMenu9.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("About");
        jMenu9.add(jMenuItem1);
        jMenu9.add(jSeparator5);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("User Manual");
        jMenu9.add(jMenuItem14);

        jMenuBar2.add(jMenu9);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMembersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMembersListActionPerformed
        AllMembers app = new AllMembers();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemMembersListActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItemApplyLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApplyLoanActionPerformed
        // TODO add your handling code here:
        //new LoanApplication().setVisible(true);
        ApplyForLoan app = new ApplyForLoan();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemApplyLoanActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        if (Member.Logout()) {
            JOptionPane.showMessageDialog(rootPane, "Youve logged out", "Bye", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new LoginScreen().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "System is experiencing problems. please try again");
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewMemberActionPerformed
        // TODO add your handling code here:
        new AddMember().setVisible(true);
    }//GEN-LAST:event_jMenuItemNewMemberActionPerformed

    private void jMenuItemCheckLoanStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheckLoanStatusActionPerformed
        // TODO add your handling code here:
        DisplayLoanInformation app = new DisplayLoanInformation();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemCheckLoanStatusActionPerformed

    private void jMenuItemMakeContribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMakeContribActionPerformed
        // TODO add your handling code here:
        MakeContribution app = new MakeContribution();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemMakeContribActionPerformed

    private void jMenuItemRepayLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepayLoanActionPerformed
        // TODO add your handling code here:
        RepayLoan adm = new RepayLoan();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemRepayLoanActionPerformed

    private void jMenuItemMemberInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMemberInfoActionPerformed
        // TODO add your handling code here:
        EditMember adm = new EditMember();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemMemberInfoActionPerformed

    private void jMenuItemMyPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMyPasswordActionPerformed
        // TODO add your handling code here:
        EditPassword adm = new EditPassword();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemMyPasswordActionPerformed

    private void jMenuItemEditInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditInterestActionPerformed
        // TODO add your handling code here:
        EditLoanInterest app = new EditLoanInterest();
        jDesktopPane1.add(app);
        app.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditInterestActionPerformed

    private void jMenuItemAllMembersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAllMembersMenuActionPerformed
        AdminEditMember adm = new AdminEditMember();
        jDesktopPane1.add(adm);
        adm.setVisible(true);
    }//GEN-LAST:event_jMenuItemAllMembersMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new SubmittQuery().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(this.getContentPane(), "Are you sure you want to exit?", "prompt", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (reply == JOptionPane.CANCEL_OPTION | reply == JOptionPane.NO_OPTION) {
            return;
        } else {
            dispose();
            Application.Exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "<html> <p>Your User Id is </p>" + Member.getId() + "<br><p> You are logged in as </p>" + m.getFirstname() + "</html>");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MembersIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            if (!Member.CheckLoggedIn()) {
                JOptionPane.showMessageDialog(null, "Please login first", "Access denied", JOptionPane.ERROR_MESSAGE);
                new LoginScreen().setVisible(true);
            } else {
                new MembersIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAdministrator;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAllMembersMenu;
    private javax.swing.JMenuItem jMenuItemApplyLoan;
    private javax.swing.JMenuItem jMenuItemApproveDenyContrib;
    private javax.swing.JMenuItem jMenuItemCheckLoanStatus;
    private javax.swing.JMenuItem jMenuItemEditInterest;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemMakeContrib;
    private javax.swing.JMenuItem jMenuItemMemberInfo;
    private javax.swing.JMenuItem jMenuItemMembersList;
    private javax.swing.JMenuItem jMenuItemMyPassword;
    private javax.swing.JMenuItem jMenuItemNewMember;
    private javax.swing.JMenuItem jMenuItemRepayLoan;
    private javax.swing.JMenuItem jMenuItemViewContrib;
    private javax.swing.JMenuItem jMenuItemViewLoans;
    private javax.swing.JMenuItem jMenuItemViewMyContributions;
    private javax.swing.JMenu jMenuMember;
    private javax.swing.JMenu jMenuReports;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
